"use client";
import {normalizeUnit} from '@/lib/iqn/catalog';
import Link from 'next/link';
import {useState} from 'react';
import {api} from '@/lib/api/client';
import {annualSourceId,roundedQuantity} from '@/lib/funding/annual';
import {useApiResource} from '@/lib/use-api-resource';
import {useAuth} from '@/components/auth-provider';
import {Badge,Button,Card,EmptyState,ErrorState,LoadingState,PageHeader,SelectInput,TableFrame,TextInput} from '@/components/ui';
const fmt=(n:number)=>new Intl.NumberFormat('uz-UZ',{maximumFractionDigits:3}).format(n);
export default function AnnualProgramPage(){
 const [year,setYear]=useState(()=>typeof window==='undefined'?new Date().getFullYear():Number(new URLSearchParams(window.location.search).get('year'))||new Date().getFullYear());
 const {user}=useAuth();const canWrite=user?.id==='demo-chief';
 const [edit,setEdit]=useState(''),[months,setMonths]=useState<number[]>(Array(12).fill(0)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[actionError,setError]=useState('');
 const {data,loading,error,reload}=useApiResource(()=>api.budgetProgram(year),`budget-annual:${year}`);
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tashkent'});
 const line=data?.lines.find(l=>l.id===edit),sum=months.reduce((s,n)=>s+n,0);
 async function save(){if(!line)return;setBusy(true);setError('');try{await api.allocateBudgetMonths(year,line.id,months);await reload();setMessage('Oylik hajmlar saqlandi. Endi shu oydan topshiriq yarating.');setEdit('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function excel(){if(!data?.program)return;setBusy(true);setError('');try{const {downloadAnnualWorkbook}=await import('@/lib/funding/annual-workbook');downloadAnnualWorkbook(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="page-stack"><PageHeader title="Yillik saqlash rejasi" description="Tasdiqlangan budjet → oylik taqsimot → topshiriq → tasdiqlangan ijro." actions={<><Link className="button button--secondary" href="/saqlash-budjeti">Saqlash budjeti</Link><SelectInput label="Yil" name="annualYear" value={year} onChange={e=>{setYear(Number(e.target.value));setEdit('');}}>{[...new Set([year-1,year,year+1,...(data?.years??[])])].sort().map(y=><option key={y} value={y}>{y}</option>)}</SelectInput><Button variant="secondary" disabled={!data?.program} busy={busy} onClick={excel}>Excel</Button></>}/>
 {message?<p className="success-banner" role="status">{message}</p>:null}{actionError?<p className="inline-error" role="alert">{actionError}</p>:null}
 {loading&&!data?<LoadingState/>:error?<ErrorState error={error} retry={reload}/>:!data?.program?<EmptyState title="Tasdiqlangan budjet yo‘q" detail="Saqlash budjetini tasdiqlang. Undagi ishlar yillik rejaga avtomatik o‘tadi."/>:<>
 <Card><div className="card-heading"><div><p className="eyebrow">{year}-yil · {data.program.revision}-tahrir</p><h2>Yillik bajarilish: {fmt(data.progress)}%</h2></div><Badge tone="success">Budjet tasdiqlangan</Badge></div><progress value={data.progress} max={100} style={{width:'100%',height:16}}/><p className="field__hint">Faqat boshliq tasdiqlagan hajm. Umumiy foiz me’yoriy mehnat soati bilan vaznlanadi; ortiqcha ishlangan vaqt foizni oshirmaydi. Har bir band foizi o‘z birligidagi hajmdan olinadi.</p><p>{data.program.approvedBy} · {data.program.approvedAt.slice(0,10)} · {fmt(data.program.total)} so‘m</p></Card>
 <Card><TableFrame label="Yillik reja nazorati"><table><thead><tr><th>Yo‘l / ish</th><th>Yillik hajm</th><th>Oylarga ajratilgan</th><th>Ijroda band</th><th>Tasdiqlangan</th><th>Qoldiq</th><th>Bajarilish</th><th/></tr></thead><tbody>{data.lines.map(l=><tr key={l.id}><td><strong>{data.program!.snapshot.roads.find(r=>r.id===l.roadId)?.code} · {l.workName}</strong><small>{l.assetName} · {l.normReference}</small></td><td>{fmt(l.quantity)} {l.unit}</td><td>{fmt(l.monthly.reduce((s,n)=>s+n,0))}</td><td>{fmt(l.reserved)}</td><td>{fmt(l.completed)}</td><td>{fmt(l.remaining)}</td><td>{fmt(l.percent)}%</td><td><Button variant="secondary" onClick={()=>{setEdit(l.id);setMonths([...l.monthly]);setError('');}}>Oylar</Button></td></tr>)}</tbody></table></TableFrame></Card>
 {line?<Card><h2>{line.workName}</h2><p>Yillik: {fmt(line.quantity)} {line.unit} · Oylarga ajratilgan: {fmt(sum)} · Ajratilmagan: {fmt(line.quantity-sum)}</p><div className="button-row">{canWrite?<Button variant="secondary" onClick={()=>{const scale=normalizeUnit(line.unit)==='dona'?1:1e6,q=Math.round(line.quantity*scale),n=Math.floor(q/12);setMonths(Array.from({length:12},(_,i)=>(n+(i<q%12?1:0))/scale));}}>12 oyga teng taqsimlash</Button>:null}</div><p className="field__hint">Mavsumiy ishlarni tegishli oylarga kiriting. Teng taqsimlash — rejalashtirish tanlovi. O‘tgan oyning qolgan hajmini keyingi oyga qayta taqsimlang.</p><TableFrame label="Oylik taqsimot"><table><thead><tr><th>Oy</th><th>Reja, {line.unit}</th><th>Band</th><th>Bajarilgan</th><th>Yil boshidan</th><th/></tr></thead><tbody>{line.months.map((m,i)=><tr key={m.month}><td>{year}-{String(m.month).padStart(2,'0')}</td><td><TextInput label={`${m.month}-oy hajmi`} name={`month-${m.month}`} type="number" min={m.used} step={normalizeUnit(line.unit)==='dona'?1:0.000001} value={months[i]} disabled={!canWrite} onChange={e=>setMonths(v=>v.map((n,j)=>i===j?Number(e.target.value):n))}/></td><td>{fmt(m.reserved)}</td><td>{fmt(m.completed)}</td><td>{fmt(line.months.slice(0,i+1).reduce((s,n)=>s+n.completed,0))}</td><td>{m.planned-m.used>0.000001&&`${year}-${String(m.month).padStart(2,'0')}`>=today.slice(0,7)?<Link className="button button--secondary" href={`/rejalashtirish?defect=${encodeURIComponent(annualSourceId(year,line.id,m.month))}&roadId=${encodeURIComponent(line.roadId)}&scheduledDate=${`${year}-${String(m.month).padStart(2,'0')}`===today.slice(0,7)?today:`${year}-${String(m.month).padStart(2,'0')}-01`}`}>Topshiriq yaratish</Link>:null}</td></tr>)}</tbody></table></TableFrame>{sum>line.quantity+.0000005?<p className="inline-error">Oylik yig‘indi yillik rejadan oshdi.</p>:null}{canWrite?<Button busy={busy} disabled={sum>line.quantity+.0000005} onClick={save}>Oylik taqsimotni saqlash</Button>:null}<Button variant="ghost" onClick={()=>setEdit('')}>Yopish</Button></Card>:null}
 {data.program.deferred?.length?<Card><details><summary>Mablag‘ yetmagan ishlar ({data.program.deferred.length})</summary><p>To‘liq ehtiyoj: {fmt(data.program.requiredTotal??data.program.total)} so‘m. Yillik ijro foizi tasdiqlangan hajmdan hisoblanadi.</p>{data.program.deferred.map(l=><p key={l.lineId}>{l.workName}: {fmt(l.quantity)} {l.unit}</p>)}</details></Card>:null}
 <Card><details><summary>Tasdiqlash tarixi</summary>{data.revisions.filter(p=>p.year===year).map(p=><p key={p.id}>{p.revision}-tahrir · {p.approvedAt.slice(0,10)} · {fmt(p.total)} so‘m · {p.state==='APPROVED'?'Amaldagi':'Avvalgi'}</p>)}</details></Card>
 </>}</div>;
}
