import React from 'react';
import {render,fireEvent,screen,waitFor,cleanup,within} from '@testing-library/react';
import assert from 'node:assert/strict';
import {handleFixtureRequest} from '../src/lib/api/fixtures';
import FundingPage from '../src/app/(app)/saqlash-budjeti/page';
export async function run(){
 await handleFixtureRequest('/auth/login',{method:'POST',body:{email:'demo@example.uz'}});
 globalThis.fetch=(async()=>Response.json({configured:false})) as typeof fetch;
 render(<FundingPage/>);
 assert.ok(await screen.findByText('Saqlash budjeti'));
 assert.ok(screen.getByText('Hisoblangan qism — to‘liq budjet emas'));
 fireEvent.change(screen.getByLabelText('Mavjud budjet, so‘m (ixtiyoriy)'),{target:{value:'-1'}});
 assert.equal((screen.getByRole('button',{name:'Excel yuklash'}) as HTMLButtonElement).disabled,true);
 fireEvent.change(screen.getByLabelText('Mavjud budjet, so‘m (ixtiyoriy)'),{target:{value:'500000000'}});
 fireEvent.click(screen.getByRole('tab',{name:'Tarif va shartlar'}));
 const annual=screen.getByLabelText('Bir xodim yillik ish vaqti, soat');fireEvent.change(annual,{target:{value:'0'}});
 await waitFor(()=>assert.ok(screen.getByRole('alert')));
 assert.ok(screen.getByLabelText('Bir xodim yillik ish vaqti, soat'),'invalid input must stay editable');
 fireEvent.change(screen.getByLabelText('Bir xodim yillik ish vaqti, soat'),{target:{value:'1976'}});
 await waitFor(()=>assert.equal(screen.queryByRole('alert'),null));
 const rate=screen.getAllByLabelText(/narxi$/)[0] as HTMLInputElement;const rateLabel=rate.id;const oldRate=rate.value;fireEvent.change(rate,{target:{value:'-1'}});await waitFor(()=>assert.ok(screen.getByRole('alert')));assert.ok(document.getElementById(rateLabel),'invalid price stays editable');fireEvent.change(document.getElementById(rateLabel)!,{target:{value:oldRate}});await waitFor(()=>assert.equal(screen.queryByRole('alert'),null));
 fireEvent.change(screen.getByLabelText('Ishchi asosiy oyligi, so‘m'),{target:{value:'4200000'}});
 fireEvent.click(screen.getByRole('button',{name:'Hisobni saqlash'}));await screen.findByRole('status');
 const saved=JSON.parse(localStorage.getItem('roadops-funding-v1')!);assert.equal(saved[0].policy.workerMonthly,4200000);assert.equal(saved[0].budgetLimit,500000000);
 fireEvent.click(screen.getByRole('tab',{name:'Yo‘llar va aktivlar'}));
 await screen.findByText('RAMS API ulanmagan. Eksport faylini yuklash mumkin.');
 const road=screen.getByRole('region',{name:'D001 aktivlari'});
 const grassRow=within(road).getByText('Yo‘l yoqasidagi o‘tlar').closest('tr')!;
 fireEvent.click(within(grassRow).getByRole('button',{name:'Ish va me’yor'}));
 assert.ok(screen.getByText('67 km ish uchun jami talab'),'mowing display converts area to2m passkm');
 fireEvent.change(screen.getByLabelText('Ishni tanlash'),{target:{value:'iqn02-t1-r14'}});
 fireEvent.change(screen.getByLabelText('Bir bajarishdagi ish hajmi, m2'),{target:{value:'134000'}});
 fireEvent.change(screen.getByLabelText('Yillik davriylik (qo‘lda o‘zgartirish)'),{target:{value:'2'}});
 fireEvent.change(screen.getByLabelText('Davriylik qarorining asosi'),{target:{value:'Yillik xizmat rejasi'}});
 fireEvent.change(screen.getByLabelText('Material ehtiyoji'),{target:{value:'NONE'}});
 fireEvent.change(screen.getByLabelText('Texnika ehtiyoji'),{target:{value:'NONE'}});
 fireEvent.change(screen.getByLabelText('Resurs hisobi asosi'),{target:{value:'Qo‘l kuchi va xodim kartochkasidagi asboblar'}});
 assert.equal(screen.getAllByText('Boshliq: talab qilinmaydi.').length,2);
 fireEvent.click(screen.getByRole('button',{name:'Hisobga qaytish'}));
 assert.ok(screen.getByText('Xodimlar va ish haqi'));
 fireEvent.change(screen.getByLabelText('Mavjud budjet, so‘m (ixtiyoriy)'),{target:{value:'0'}});
 fireEvent.click(screen.getByRole('button',{name:'Ochish'}));
 assert.equal((screen.getByLabelText('Mavjud budjet, so‘m (ixtiyoriy)') as HTMLInputElement).value,'500000000');
 let downloaded:Blob|undefined,filename='';const oldUrl=URL.createObjectURL,oldClick=window.HTMLAnchorElement.prototype.click;
 URL.createObjectURL=(blob:Blob)=>{downloaded=blob;return 'blob:test-funding';};
 window.HTMLAnchorElement.prototype.click=function(){filename=this.download;};
 fireEvent.click(screen.getByRole('button',{name:'Excel yuklash'}));
 await waitFor(()=>assert.ok(downloaded));
 assert.ok(filename.endsWith('.xlsx'));assert.equal(downloaded!.type,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
 const bytes=new Uint8Array(await downloaded!.arrayBuffer());assert.equal(bytes[0],80);assert.equal(bytes[1],75);
 URL.createObjectURL=oldUrl;window.HTMLAnchorElement.prototype.click=oldClick;
 const selected=screen.getAllByRole('checkbox').filter((x:HTMLElement)=>(x as HTMLInputElement).checked);
 for(const box of selected)fireEvent.click(box);
 assert.equal((screen.getByRole('button',{name:'Excel yuklash'}) as HTMLButtonElement).disabled,true);
 cleanup();
 console.log('PASS: funding flow, real XLSX download, limit persistence and invalid/empty input guards');
}
