import React from 'react';
import {render,fireEvent,screen,waitFor,cleanup,within} from '@testing-library/react';
import assert from 'node:assert/strict';
import ManualEntryPage from '../src/app/(app)/malumot-kiritish/page';
import DefectsPage from '../src/app/(app)/tasdiqlangan-nuqsonlar/page';
import {PlanResources} from '../src/components/plan-resources';
import {resourceChoices} from '../src/lib/iqn/resource-plan';
import {api} from '../src/lib/api/client';
import PlanningPage from '../src/app/(app)/rejalashtirish/page';
import {handleFixtureRequest} from '../src/lib/api/fixtures';
async function receiveSupply(){
 const requests:any=await handleFixtureRequest('/resource-requisitions',{}),request=requests.items.find((r:any)=>r.status==='SUBMITTED');
 assert.ok(request);
 await handleFixtureRequest('/demo/role',{method:'POST',body:{role:'engineer'}});
 await handleFixtureRequest(`/resource-requisitions/${request.id}/decision`,{method:'POST',body:{decision:'APPROVE',note:'Ta’minot'}});
 await handleFixtureRequest(`/demo/requisitions/${request.id}/receive`,{method:'POST'});
 await handleFixtureRequest('/demo/role',{method:'POST',body:{role:'chief'}});
}
export async function run(){
 // Hosted AI is not configured in these demo-flow cases; never call a live model.
 globalThis.fetch=(async(path)=>{assert.equal(path,'/api/ai/status');return Response.json({data:{configured:false}});}) as typeof fetch;
 await handleFixtureRequest('/auth/login',{method:'POST',body:{email:'operator@example.uz',password:'e2e-password'}});
 await handleFixtureRequest('/demo/role',{method:'POST',body:{role:'chief'}});
 const options:any=await handleFixtureRequest('/planning/options?roadId=road-d001',{});
 const source=options.sourceDefects.find((s:any)=>s.suggestedWorkVariantIds?.includes('work-pothole'));
 render(<PlanningPage/>);
 await waitFor(()=>assert.ok(screen.getByLabelText('Nuqson yoki yillik reja bandi')));
 fireEvent.change(screen.getByLabelText('Nuqson yoki yillik reja bandi'),{target:{value:source.id}});
 fireEvent.click(screen.getByRole('button',{name:'Ish turiga o‘tish'}));
 const select=screen.getByLabelText('IQN 02-24 bo‘yicha ish turi') as HTMLSelectElement;
 assert.ok(select.options.length>500,'full source catalog must be selectable');
 fireEvent.change(screen.getByLabelText('Ish nomi yoki kodi'),{target:{value:'2-1-1'}});
 fireEvent.change(select,{target:{value:'iqn02-t2-r4'}});
 const tomorrow=new Date(Date.now()+86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Tashkent'});
 fireEvent.change(screen.getByLabelText('Boshlanish sanasi'),{target:{value:tomorrow}});
 await waitFor(()=>assert.equal((screen.getByRole('button',{name:'Xodimlarni tanlash'}) as HTMLButtonElement).disabled,false));
 assert.equal((screen.getByLabelText('IQN 02-24 bo‘yicha ish turi') as HTMLSelectElement).value,'iqn02-t2-r4','changing dates retains the selected work');
 // Requirements are visible before calculating a draft and scale immediately.
 const materials=screen.getByRole('region',{name:'Materiallar'});
 assert.ok(materials.textContent?.includes('45059'));
 assert.equal(within(screen.getByRole('region',{name:'Mashina-mexanizmlar'})).getAllByRole('listitem').length,5);
 assert.equal(screen.queryByLabelText('Material ehtiyoji'),null,'verified source recipe needs no manual entry');
 fireEvent.change(screen.getByLabelText(/Ish hajmi/),{target:{value:'2'}});
 assert.ok(materials.textContent?.includes('0,234')||materials.textContent?.includes('0.234'));
 fireEvent.change(screen.getByLabelText(/Ish hajmi/),{target:{value:'4'}});
 fireEvent.change(screen.getByLabelText('Ish nomi yoki kodi'),{target:{value:''}});
 fireEvent.change(select,{target:{value:'iqn02-t2-r15'}});
 assert.equal(within(screen.getByRole('region',{name:'Mashina-mexanizmlar'})).getAllByRole('listitem').length,3,'changing to a no-demolition job removes the hammer and compressor');
 fireEvent.change(select,{target:{value:'iqn02-t2-r4'}});
 fireEvent.click(screen.getByRole('button',{name:'Xodimlarni tanlash'}));
 fireEvent.click(screen.getByRole('button',{name:'Resurslarni tekshirish'}));
 await waitFor(()=>assert.ok(screen.getByRole('button',{name:'Bosh muhandisga yuborish'})));
 assert.equal(screen.queryByRole('button',{name:'Resurs tarkibini belgilash'}),null);
 fireEvent.click(await screen.findByRole('button',{name:'Bosh muhandisga yuborish'}));
 await screen.findByText('Bosh muhandis ta’minoti kutilmoqda');
 await receiveSupply();
 fireEvent.click(screen.getByRole('button',{name:'Qayta tekshirish'}));
 await waitFor(()=>assert.equal((screen.getByRole('button',{name:'Yakuniy tekshiruv'}) as HTMLButtonElement).disabled,false));
 fireEvent.click(screen.getByRole('button',{name:'Yakuniy tekshiruv'}));
 await waitFor(()=>assert.ok(screen.getByRole('button',{name:'Tasdiqlash va ijroga berish'})));
 fireEvent.click(screen.getByRole('button',{name:'Tasdiqlash va ijroga berish'}));
 await waitFor(()=>assert.ok(screen.getByText('Topshiriq yo‘l ustasiga berildi. Endi ijro boshlanadi.')));
 const orders:any=await handleFixtureRequest('/work-orders?pageSize=100',{});
 assert.ok(orders.items.some((o:any)=>o.sourceDefectId===source.id&&o.state==='ASSIGNED'));
 cleanup();
 const unmapped=options.workVariants.find((w:any)=>w.id==='iqn02-t2-r6');
 const none={workVariantId:unmapped.id,basisQuantity:'4',note:'Joyidagi tasdiqlangan hisob',materials:{mode:'NONE' as const,items:[]},machines:{mode:'NONE' as const,items:[]}};
 render(<PlanResources work={unmapped} catalog={options.workVariants} quantity="4" value={none} onChange={()=>{}}/>);
 assert.equal(screen.getAllByText('Boshliq: talab qilinmaydi.').length,2);assert.equal(screen.queryByText('Sarf me’yori kiritilmagan.'),null);cleanup();
 const winter=options.workVariants.find((w:any)=>w.code==='27-14-079-01'),choices=resourceChoices(options.workVariants),sand=choices.find(c=>c.kind==='material')!;
 render(<PlanResources work={winter} catalog={options.workVariants} quantity="8" value={{workVariantId:winter.id,basisQuantity:'4',note:'Texnologik karta',materials:{mode:'REQUIRED',items:[{key:sand.key,quantity:'0.1'}]}}} onChange={()=>{}}/>);
 assert.ok(screen.getByText('IQN + boshliq hisobi'));assert.ok(within(screen.getByRole('region',{name:'Materiallar'})).getByText(/Boshliq hisobi/));assert.equal(within(screen.getByRole('region',{name:'Mashina-mexanizmlar'})).getAllByRole('listitem').length,2);cleanup();
 const leveling=options.workVariants.find((w:any)=>w.id==='iqn02-r-27-14-026-01-t98');
 render(<PlanResources work={leveling} catalog={options.workVariants} quantity="4" onChange={()=>{}}/>);
 assert.equal(screen.getAllByText('Sarf me’yori kiritilmagan.').length,2);cleanup();
 // A new foreman record keeps IQN type/measurements and reaches a prepared AI demo draft.
 window.history.replaceState({},'', '/malumot-kiritish');
 render(<ManualEntryPage/>);
 const typeSelect=await screen.findByLabelText('Nuqson turi') as HTMLSelectElement;
 assert.equal(typeSelect.options.length,54);
 fireEvent.change(typeSelect,{target:{value:'defect-pothole'}});
 fireEvent.change(screen.getByLabelText('Lokatsiya'),{target:{value:'25000'}});
 fireEvent.change(screen.getByLabelText('O‘lchangan nuqson hajmi, kvadrat metr'),{target:{value:'2'}});
 fireEvent.change(screen.getByLabelText('Ta’mir qalinligi, mm'),{target:{value:'50'}});
 fireEvent.change(screen.getByLabelText(/^Eng katta bitta chuqurcha, m²/),{target:{value:'1'}});
 fireEvent.change(screen.getByLabelText('Eski qoplamani buzish'),{target:{value:'true'}});
 fireEvent.submit(typeSelect.closest('form')!);
 await waitFor(()=>assert.equal(window.location.pathname,'/tasdiqlangan-nuqsonlar'));
 cleanup();
 render(<DefectsPage/>);
 const pending:any=await handleFixtureRequest('/manual-inspections?state=PENDING_REVIEW',{});
 const record=pending.items.find((r:any)=>r.observations[0].locationLabel==='25+000');
 const row=(await screen.findByText(record.inspectionNumber)).closest('tr')!;
 fireEvent.click(within(row).getByRole('button',{name:'Tekshirish'}));
 fireEvent.click(screen.getByRole('button',{name:'Tasdiqlash va topshiriq yaratish'}));
 await waitFor(()=>assert.equal(window.location.pathname,'/rejalashtirish'));
 const createdSource=new URLSearchParams(window.location.search).get('defect');assert.ok(createdSource);
 cleanup();
 render(<PlanningPage/>);
 await waitFor(()=>assert.equal((screen.getByLabelText('IQN 02-24 bo‘yicha ish turi') as HTMLSelectElement).value,'iqn02-r-27-14-023-01-t45'));
 assert.equal((screen.getByLabelText('Ta’mir qalinligi, mm') as HTMLSelectElement).value,'50');
 assert.equal((screen.getByRole('button',{name:'Loyihani ko‘rish'}) as HTMLButtonElement).disabled,false);
 fireEvent.click(screen.getByRole('button',{name:'Loyihani ko‘rish'}));
 await waitFor(()=>assert.ok(screen.getByRole('button',{name:'Bosh muhandisga yuborish'})));
 fireEvent.click(screen.getByRole('button',{name:'Bosh muhandisga yuborish'}));
 await waitFor(()=>assert.ok(screen.getByText('Bosh muhandis ta’minoti kutilmoqda')));
 await receiveSupply();
 fireEvent.click(screen.getByRole('button',{name:'Qayta tekshirish'}));
 await waitFor(()=>assert.equal((screen.getByRole('button',{name:'Yakuniy tekshiruv'}) as HTMLButtonElement).disabled,false));
 fireEvent.click(screen.getByRole('button',{name:'Yakuniy tekshiruv'}));
 fireEvent.click(await screen.findByRole('button',{name:'Tasdiqlash va ijroga berish'}));
 await screen.findByText('Topshiriq yo‘l ustasiga berildi. Endi ijro boshlanadi.');
 cleanup();
 // Missing RoadVision quantities start in the expected unit and can be reclassified by a chief.
 await handleFixtureRequest('/roadvision/demo/import',{method:'POST'});
 window.history.replaceState({},'', '/tasdiqlangan-nuqsonlar');render(<DefectsPage/>);
 const rvRow=(await screen.findByText('RV-DEMO-2')).closest('tr')!;
 fireEvent.click(within(rvRow).getByRole('button',{name:'Tekshirish'}));
 assert.equal((screen.getByLabelText('Birlik') as HTMLSelectElement).value,'m');
 fireEvent.change(screen.getByLabelText('Tasdiqlanadigan nuqson turi'),{target:{value:'defect-sign-dirty'}});
 assert.equal((screen.getByLabelText('Birlik') as HTMLSelectElement).value,'dona');
 cleanup();
 // A slow response must not overwrite a chief's edited road-access decision.
 const sourceOptions:any=await handleFixtureRequest('/planning/options?roadId=road-d001',{});
 const openSource=sourceOptions.sourceDefects.find((s:any)=>s.suggestedWorkVariantIds?.includes('work-shoulder'));
 window.history.replaceState({},'', '/rejalashtirish');
 const originalRecommend=api.aiWorkRecommendation;let resolveRequest:any;
 api.aiWorkRecommendation=((...args:any[])=>new Promise(resolve=>{resolveRequest=()=>originalRecommend(...args as [string,string]).then(resolve);})) as typeof originalRecommend;
 render(<PlanningPage/>);
 fireEvent.change(await screen.findByLabelText('Nuqson yoki yillik reja bandi'),{target:{value:openSource.id}});
 fireEvent.click(screen.getByRole('button',{name:'Ish turiga o‘tish'}));
 await waitFor(()=>assert.ok(resolveRequest));
 fireEvent.change(screen.getByLabelText('Ish vaqtida yo‘l harakati'),{target:{value:'CLOSED'}});
 await resolveRequest();
 await waitFor(()=>assert.equal((screen.getByLabelText('Ish vaqtida yo‘l harakati') as HTMLSelectElement).value,'CLOSED'));
 api.aiWorkRecommendation=originalRecommend;
 cleanup();
 // A configured model is visibly distinct, and its explanation/provenance reach the draft.
 const aiOptions:any=await handleFixtureRequest('/planning/options?roadId=road-d001',{});
 const aiSource=aiOptions.sourceDefects.find((s:any)=>s.suggestedWorkVariantIds?.includes('work-shoulder'));
 let observedRequest:any;
 globalThis.fetch=(async(path,init)=>{
   if(path==='/api/ai/status')return Response.json({data:{configured:true}});
   assert.equal(path,'/api/ai/work-selection');observedRequest=JSON.parse(String(init?.body));
   return Response.json({data:{mode:'OPENAI',workVariantId:'iqn02-t1-r5',explanation:'Ko‘rik va birlik tanlangan IQN ishiga mos.',missingFields:[],checks:['Birlik mos'],model:'test-model',analysisId:'test-analysis',createdAt:new Date().toISOString()}});
 }) as typeof fetch;
 window.history.replaceState({},'', `/rejalashtirish?defect=${aiSource.id}`);
 render(<PlanningPage/>);
 await screen.findByText('Haqiqiy AI');
 fireEvent.change(screen.getByRole('textbox',{name:/^Qo‘shimcha ko‘rik ma’lumoti/}),{target:{value:'Yo‘l yoqasi cho‘kkan, tuproq bilan to‘ldirish kerak.'}});
 assert.equal(screen.queryByText('Haqiqiy AI'),null);
 assert.equal((screen.getByRole('button',{name:'Loyihani ko‘rish'}) as HTMLButtonElement).disabled,true,'A changed answer invalidates the old work');
 fireEvent.click(screen.getByRole('button',{name:'AI tavsiyasini yangilash'}));
 await screen.findByText('Haqiqiy AI');assert.match(observedRequest.inspectionNote,/tuproq/);
 const proposal=await api.aiWorkRecommendation(aiSource.id,new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tashkent'}),{},undefined,observedRequest.inspectionNote);
 assert.equal(proposal.input?.workSelectionSource,'AI');assert.equal(proposal.input?.aiAnalysis?.id,'test-analysis');
 assert.equal(proposal.preview?.resourcesReady,false,'AI cannot bypass unknown resources');
 const draft=await api.previewManualPlan(proposal.input!);
 assert.equal((await api.planInput(draft.draftId)).aiInspectionNote,observedRequest.inspectionNote);
 // Provider failure is an error, not a fabricated successful AI result.
 globalThis.fetch=(async(path)=>path==='/api/ai/status'?Response.json({data:{configured:true}}):Response.json({error:{message:'AI xizmati rad etdi.'}},{status:503})) as typeof fetch;
 fireEvent.click(screen.getByRole('button',{name:'AI tavsiyasini yangilash'}));
 await screen.findByText('AI xizmati rad etdi.');assert.equal(screen.queryByText('Haqiqiy AI'),null);
 cleanup();
 console.log('PASS: full catalog; capture → review → demo draft → supply → dispatch; RoadVision units; stale-response protection; mocked AI provenance, clarification and provider failure');
}
