"use client";
import {useState} from 'react';
import {coverageRows} from '@/lib/funding/coverage';
import type {AssetSnapshot,FundingPolicy,FundingResult} from '@/lib/funding/types';
import {Card,SelectInput,TextInput} from './ui';
export function FundingCoverage({snapshot,policy,result,onChange,disabled}:{snapshot:AssetSnapshot;policy:FundingPolicy;result:FundingResult;onChange:(p:Partial<FundingPolicy>)=>void;disabled:boolean}){
 const [scope,setScope]=useState(''),[group,setGroup]=useState('topics');
 const rows=coverageRows(snapshot,policy,result),scopes=[...new Set(rows.map(r=>r.scopeLabel))],selected=scopes.includes(scope)?scope:scopes[0];
 const shown=rows.filter(r=>(group==='organization'?r.scope==='organization':r.scopeLabel===selected&&r.scope==='road')&&(group==='annex'?r.id.startsWith('annex1'):group==='topics'?r.id.startsWith('iqn02-topic'):true));
 const edit=(key:string,patch:Partial<NonNullable<FundingPolicy['coverage']>[string]>)=>onChange({coverage:{...policy.coverage,[key]:{state:'INCLUDED',reason:'',...policy.coverage?.[key],...patch}}});
 return <Card><h2>IQN qamrovi: {rows.filter(r=>!r.issue).length} / {rows.length}</h2><p>Har bir yo‘nalish va davriy ishni tekshiring. Hisobdagi bandlarni bog‘lang yoki qo‘llanmaslik sababini yozing. “Kiritilgan” — shu yo‘nalishning barcha zarur ishlari tekshirildi degani.</p><div className="funding-form-grid"><SelectInput label="Tekshiruv" name="coverageGroup" value={group} onChange={e=>setGroup(e.target.value)}><option value="topics">IQN 02-24: 29 yo‘nalish</option><option value="annex">IQN 02-24: 1-ilova davriyligi</option><option value="organization">IQN 03-24: shtat va xarajatlar</option></SelectInput>{group!=='organization'?<SelectInput label="Yo‘l" name="coverageRoad" value={selected??''} onChange={e=>setScope(e.target.value)}>{scopes.filter(s=>s!=='Tashkilot').map(s=><option key={s} value={s}>{s}</option>)}</SelectInput>:null}</div><fieldset disabled={disabled} className="funding-fieldset">{shown.map(r=><details key={r.key} className="coverage-item"><summary>{r.issue?'○':'✓'} {r.name}</summary><p className="field__hint">{r.source}</p><SelectInput label="Qamrov qarori" name={`coverage-${r.key}`} value={r.decision?.state??''} onChange={e=>edit(r.key,{state:e.target.value as 'INCLUDED'|'NOT_APPLICABLE'})}><option value="" disabled>Tekshirilmagan</option><option value="INCLUDED">Zarur ishlar hisobga kiritilgan</option><option value="NOT_APPLICABLE">Bu qamrovda talab etilmaydi</option></SelectInput><TextInput label="Qamrov, istisno yoki qaror asosi" name={`coverage-note-${r.key}`} value={r.decision?.reason??''} onChange={e=>edit(r.key,{reason:e.target.value})}/>{r.decision?.state==='INCLUDED'&&r.scope==='road'?<><p>Hisobdagi tegishli ish bandlari:</p>{r.available.length?r.available.map(l=><label key={l.id} className="coverage-link"><input type="checkbox" checked={r.decision?.lineIds?.includes(l.id)??false} onChange={e=>edit(r.key,{lineIds:e.target.checked?[...(r.decision?.lineIds??[]),l.id]:(r.decision?.lineIds??[]).filter(id=>id!==l.id)})}/>{l.assetName} · {l.workName}</label>):<p className="inline-error">Mos ish yo‘q. “Yo‘llar va aktivlar”da alohida ish bandini qo‘shing.</p>}</>:null}{r.issue?<p className="field__hint">{r.issue}</p>:null}</details>)}</fieldset></Card>;
}
