"use client";
import {useEffect,useMemo,useState} from 'react';
import {Download,RefreshCw,Save,Upload} from 'lucide-react';
import {Badge,Button,Card,PageHeader,SelectInput,TableFrame,TextInput,TextArea} from '@/components/ui';
import {useAuth,useHasPermission} from '@/components/auth-provider';
import Link from 'next/link';
import {api} from '@/lib/api/client';
import {FundingCoverage} from '@/components/funding-coverage';
import {approvalIssues} from '@/lib/funding/coverage';
import {staffRoles} from '@/lib/funding/equipment';
import {PlanResources} from '@/components/plan-resources';
import {iqnWorkCatalog} from '@/lib/iqn/catalog';
import {assetLabels,conditionLabels,importanceLabels,equipmentNorms} from '@/lib/funding/norms';
import {assetWorkSpecs,calculateFunding,fleetRequirements} from '@/lib/funding/calculate';
import {allocateBudget,parseBudgetLimit} from '@/lib/funding/allocation';
import {defaultPolicy,demoSnapshot,parseAssetSnapshot} from '@/lib/funding/assets';
import type {Asset,AssetSnapshot,FundingPolicy,ResourceCost,Road} from '@/lib/funding/types';
import './styles.css';
const money=(n:number)=>new Intl.NumberFormat('uz-UZ',{maximumFractionDigits:0}).format(n);
const number=(n:number)=>new Intl.NumberFormat('uz-UZ',{maximumFractionDigits:3}).format(n);
const storageKey='roadops-funding-v1';
type Saved={id:string;at:string;snapshot:AssetSnapshot;policy:FundingPolicy;budgetLimit?:number|null};
function download(value:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function FundingPage(){
 const [snapshot,setSnapshot]=useState<AssetSnapshot>(()=>demoSnapshot());
 const [policy,setPolicy]=useState<FundingPolicy>(()=>defaultPolicy(demoSnapshot()));
 const [tab,setTab]=useState<'estimate'|'assets'|'prices'|'coverage'>('estimate');
 const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<Saved[]>([]),[activeAsset,setActiveAsset]=useState('');
 const [integration,setIntegration]=useState<'loading'|'ready'|'missing'|'error'>('loading');
 const [limit,setLimit]=useState(''),[exporting,setExporting]=useState(false);
 const limitCheck=useMemo(()=>{try{return {value:parseBudgetLimit(limit),error:''};}catch(e){return {value:null,error:(e as Error).message};}},[limit]);
 const canWrite=useHasPermission('costs.write');const {user}=useAuth();const canApprove=user?.id==='demo-chief';const [approvedYear,setApprovedYear]=useState<number|null>(null);
 useEffect(()=>{let cancelled=false;fetch('/api/funding/status').then(r=>r.json()).then(r=>{if(!cancelled)setIntegration(r.configured?'ready':'missing');}).catch(()=>{if(!cancelled)setIntegration('error');});try{const raw=localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw);if(Array.isArray(saved)){const valid=saved.filter((item:Saved)=>{try{if(!item||!item.policy)return false;parseAssetSnapshot(item.snapshot);calculateFunding(item.snapshot,item.policy);parseBudgetLimit(item.budgetLimit);return true;}catch{return false;}}).slice(0,10);setHistory(valid);}}}catch{setMessage('Avvalgi hisoblarni o‘qib bo‘lmadi. Yangi hisobdan davom eting.');}return()=>{cancelled=true;};},[]);
 const calculation=useMemo(()=>{try{return {result:calculateFunding(snapshot,policy),error:''};}catch(e){return {result:null,error:e instanceof Error?e.message:'Hisob xatosi'};}},[snapshot,policy]);
 const result=calculation.result;const approvalProblems=result?approvalIssues(snapshot,policy,result,limitCheck.value):[];
 const [resourceRows,setResourceRows]=useState<ResourceCost[]>([]);
 useEffect(()=>{if(result)setResourceRows(result.resources);},[result]);
 const selectedRoads=snapshot.roads.filter(r=>policy.roadSelection.includes(r.id));
 const fleet=useMemo(()=>fleetRequirements(selectedRoads),[selectedRoads]);
 const selection=selectedRoads.flatMap(road=>road.assets.map(asset=>({road,asset}))).find(v=>`${v.road.id}:${v.asset.id}`===activeAsset);
 const currentWork=selection?iqnWorkCatalog.find(w=>w.id===(selection.asset.workId||result?.lines.find(l=>l.assetId===selection.asset.id&&l.roadId===selection.road.id)?.workId)):undefined;
 const patch=(changes:Partial<FundingPolicy>)=>{setPolicy(p=>({...p,...changes}));setMessage('');};
 const editRoad=(id:string,changes:Partial<Road>)=>{setSnapshot(s=>({...s,roads:s.roads.map(r=>r.id===id?{...r,...changes}:r)}));setMessage('');};
 const editAsset=(roadId:string,assetId:string,changes:Partial<Asset>)=>{setSnapshot(s=>({...s,roads:s.roads.map(r=>r.id===roadId?{...r,assets:r.assets.map(a=>a.id===assetId?{...a,...changes}:a)}:r)}));setMessage('');};
 async function sync(){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/funding/assets');const data=await response.json();if(!response.ok)throw new Error(data.error||'RAMS ma’lumoti olinmadi.');const next=parseAssetSnapshot(data.data,'RAMS');setSnapshot(next);patch({roadSelection:next.roads.map(r=>r.id)});setActiveAsset('');setMessage(`${next.roads.length} ta yo‘l RAMS’dan olindi. Tariflar saqlandi.`);}catch(e){setError(e instanceof Error?e.message:'Ulanish xatosi');}finally{setBusy(false);}}
 async function importFile(file?:File){if(!file)return;setError('');try{if(file.size>5_000_000)throw new Error('Fayl 5 MB dan oshmasin.');const raw=JSON.parse(await file.text());const next=parseAssetSnapshot(raw.snapshot??raw);if(raw.snapshot&&raw.policy){calculateFunding(next,raw.policy);const nextLimit=parseBudgetLimit(raw.budgetLimit);setPolicy(raw.policy);setLimit(nextLimit===null?'':String(nextLimit));}else patch({roadSelection:next.roads.map(r=>r.id)});setSnapshot(next);setActiveAsset('');setMessage(`${next.roads.length} ta yo‘l import qilindi. Tariflarni tekshiring.`);}catch(e){setError(e instanceof Error?e.message:'Fayl o‘qilmadi.');}}
 async function approve(){if(!result||!canApprove)return;setBusy(true);setError('');try{const response=await api.approveBudget(snapshot,policy,limitCheck.value);setApprovedYear(policy.year);setMessage(`${policy.year}-yil budjeti ${response.reused?'avval tasdiqlangan':'tasdiqlandi'}. Yillik reja: ${response.program.lines.length} ta ish bandi.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function save(){if(!result||!canWrite||limitCheck.error)return;setError('');try{const record:Saved={id:crypto.randomUUID(),at:new Date().toISOString(),snapshot:structuredClone(snapshot),policy:structuredClone(policy),budgetLimit:limitCheck.value};const rows=[record,...history].slice(0,10);localStorage.setItem(storageKey,JSON.stringify(rows));setHistory(rows);setMessage('Hisob shu brauzerda saqlandi. Nusxasini yuklab olish ham mumkin.');}catch{setError('Hisob saqlanmadi. Nusxasini faylga yuklab oling.');}}
 async function exportExcel(){if(!result||limitCheck.error||exporting)return;setExporting(true);setError('');try{const {downloadFundingWorkbook}=await import('@/lib/funding/export-workbook');downloadFundingWorkbook(snapshot,policy,limitCheck.value);setMessage('Excel fayli tayyor. Jamlama va 7 ta hisob varag‘i yuklandi.');}catch(e){setError(e instanceof Error?e.message:'Excel fayli yaratilmadi. Qayta urinib ko‘ring.');}finally{setExporting(false);}}
 const field=(key:keyof FundingPolicy,label:string,nullable=false)=> <TextInput label={label} name={`budget-${key}`} type="number" min="0" step="any" value={policy[key]===null?'':String(policy[key])} onChange={e=>patch({[key]:nullable&&e.target.value===''?null:Number(e.target.value)})}/>;
 const allocations=result?allocateBudget(result,limitCheck.value):null;
 return <div className="page-stack funding-page">
  <PageHeader title="Saqlash budjeti" description="Yo‘l aktivlari → yillik ishlar → xodim va resurslar → mablag‘." actions={<><Button variant="secondary" onClick={exportExcel} busy={exporting} disabled={!result||Boolean(limitCheck.error)}><Download size={16}/> Excel yuklash</Button>{canWrite?<Button onClick={save} disabled={!result||Boolean(limitCheck.error)}><Save size={16}/> Hisobni saqlash</Button>:null}</>}/>
  <div className="funding-toolbar"><div className="funding-tabs" role="tablist" aria-label="Budjet bo‘limlari">{([['estimate','Hisob'],['assets','Yo‘llar va aktivlar'],['prices','Tarif va shartlar'],['coverage','IQN qamrovi']] as const).map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><Badge tone={snapshot.mode==='DEMO'?'warning':'info'}>{snapshot.mode==='DEMO'?'Namuna ma’lumot':snapshot.mode==='RAMS'?'RAMS ma’lumoti':'Import ma’lumoti'}</Badge></div>
  {message?<p className="success-banner" role="status">{message}</p>:null}{error||calculation.error||limitCheck.error?<p className="inline-error" role="alert">{error||calculation.error||limitCheck.error}</p>:null}
  <Card><div className="funding-topline"><div><strong>{snapshot.source}</strong><p className="field__hint">Tekshiruv: {snapshot.observedAt} · {selectedRoads.length} ta yo‘l · {number(selectedRoads.reduce((s,r)=>s+r.lengthKm,0))} km</p></div><SelectInput label="Hisob yili" name="fundingYear" value={policy.year} disabled={!canWrite} onChange={e=>patch({year:Number(e.target.value)})}>{[policy.year-1,policy.year,policy.year+1].map(y=><option key={y}>{y}</option>)}</SelectInput></div><div className="funding-road-picks">{snapshot.roads.map(r=><label key={r.id}><input type="checkbox" checked={policy.roadSelection.includes(r.id)} disabled={!canWrite} onChange={e=>patch({roadSelection:e.target.checked?[...policy.roadSelection,r.id]:policy.roadSelection.filter(id=>id!==r.id)})}/><span>{r.code}<small>{importanceLabels[r.importance]} · {r.category} · {r.lengthKm} km</small></span></label>)}</div></Card>
  {tab==='coverage'&&result?<FundingCoverage snapshot={snapshot} policy={policy} result={result} onChange={patch} disabled={!canWrite}/>:null}
  {tab==='estimate'&&result?<>
   <Card><div className="funding-topline"><div><h2>Budjet → yillik reja</h2><p className="field__hint">{approvalProblems.length?`${approvalProblems.length} ta me’yor, narx yoki qamrov aniqlashtirilishi kerak.`:'Hisob va IQN qamrovi tekshirilgan.'}</p></div><div className="button-row"><Button variant="secondary" onClick={()=>setTab('coverage')}>IQN qamrovini tekshirish</Button>{canApprove?<Button busy={busy} disabled={Boolean(approvalProblems.length)||Boolean(limitCheck.error)} onClick={approve}>Budjetni tasdiqlash</Button>:null}{approvedYear?<Link className="button button--secondary" href={`/yillik-dastur?year=${approvedYear}`}>Yillik rejaga o‘tish</Link>:null}</div></div></Card>
   <div className="funding-total"><div><p>{result.complete?'Yillik mablag‘ ehtiyoji':'Hisoblangan qism — to‘liq budjet emas'}</p><strong>{money(result.total)} <span>so‘m</span></strong><small>{/namuna/i.test(policy.reference)||result.resources.some(r=>/namuna/i.test(r.source))?'Namuna tariflar. Real ajratmadan oldin narxlar va aktivlarni almashtiring.':`${policy.year}-yil · ${result.complete?'hisob shartlari asosida':'yetishmagan me’yor va narxlarni to‘ldiring'}`}</small></div><div><span>Ishchilar</span><b>{result.workers}</b><span>Mashinist / haydovchi</span><b>{result.operators}</b><span>Yo‘l ustalari</span><b>{result.payrollRows[2]!.count}</b></div></div>
   <div className="funding-cost-grid">{[['Ish haqi',result.labor],['Material',result.materials],['Mashina-mexanizm',result.machinery],['Jihoz va asboblar',result.ppe],['Ijtimoiy xarajat',result.employerTax],['Boshqa va ustama xarajat',result.other+result.overhead],['Zaxira',result.contingency]].map(([label,value])=><Card key={String(label)}><span>{label}</span><strong>{money(Number(value))}</strong><small>so‘m / yil</small><div className="funding-bar"><i style={{width:`${result.total?Number(value)/result.total*100:0}%`}}/></div></Card>)}</div>
   {result.gaps.length?<Card><details open={result.gaps.length<5}><summary className="funding-gap-title">{result.gaps.length} ta aniqlashtirish kerak</summary><ul className="funding-gaps">{result.gaps.map(g=><li key={g}>{g}</li>)}</ul></details><Button variant="secondary" onClick={()=>setTab('assets')}>Aktiv va me’yorlarni to‘ldirish</Button></Card>:null}
   <Card><div className="card-heading"><h2>Xodimlar va ish haqi</h2><span>{number(result.workerHours+result.operatorHours)} odam-soat / yil</span></div><TableFrame label="Yillik ish haqi"><table><thead><tr><th>Xodim toifasi</th><th>Stavka / odam</th><th>Bir stavka oyligi</th><th>Yillik ish haqi</th></tr></thead><tbody>{result.payrollRows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.count} / {r.heads??r.count}</td><td>{money(r.monthly)} so‘m</td><td>{money(r.annual)} so‘m</td></tr>)}</tbody></table></TableFrame><p className="field__hint">Jami ish hajmi ÷ {policy.annualHours} soat; shtat tashkilot bo‘yicha bir marta yaxlitlanadi. Usta: {policy.supervisors===null?'IQN 03-24, 10.3-band — 20 km uchun 1 nafar':'kiritilgan shtat'}. Ish vaqti, koeffitsiyent va qo‘shimcha to‘lovlar “Tarif va shartlar”da.</p></Card>
   <Card><div className="card-heading"><h2>Yo‘llar bo‘yicha ajratma</h2><TextInput label="Mavjud budjet, so‘m (ixtiyoriy)" name="budgetLimit" type="number" min="0" step="0.01" value={limit} onChange={e=>setLimit(e.target.value)}/></div><TableFrame label="Yo‘llarga mablag‘"><table><thead><tr><th>Yo‘l</th><th>Ahamiyati / holati</th><th>Ehtiyoj</th>{limitCheck.value!==null?<><th>Ajratish ssenariysi</th><th>Yetishmaydi</th></>:null}</tr></thead><tbody>{allocations!.roads.map(row=>{const road=snapshot.roads.find(r=>r.id===row.id)!;return <tr key={row.id}><td><strong>{row.code}</strong><small>{row.lineCount} ish bandi{row.missing?` · ${row.missing} ta aniqlashtirish`:null}</small></td><td>{importanceLabels[road.importance]} · {road.category}<small>{conditionLabels[road.condition]}</small></td><td>{money(row.amount)}</td>{limitCheck.value!==null?<><td>{money(row.allocated!)}</td><td>{money(row.shortfall!)}</td></>:null}</tr>;})}</tbody></table></TableFrame><p className="field__hint">Cheklangan budjet ssenariysi ahamiyat va holat ustuvorligida taqsimlanadi. Bu IQN koeffitsiyenti yoki tasdiqlangan ajratma emas. Umumiy xarajatlar bevosita xarajat ulushida taqsimlanadi.</p>{allocations?.unallocated!==null&&allocations?.unallocated!==undefined&&allocations.unallocated>0?<p className="field__hint">Taqsimlanmagan qoldiq: <strong>{money(allocations.unallocated)} so‘m</strong></p>:null}</Card>
   <Card><h2>Mablag‘ qaysi ishlarga sarflanadi?</h2><TableFrame label="Yillik ishlar hisob-kitobi"><table><thead><tr><th>Yo‘l / aktiv</th><th>Ish turi</th><th>Yillik hajm</th><th>Ishchi / mashinist soati</th><th>Bevosita xarajat</th><th>Asos</th></tr></thead><tbody>{result.lines.map(l=><tr key={l.id}><td>{snapshot.roads.find(r=>r.id===l.roadId)!.code}<small>{l.assetName}</small></td><td>{l.workName}{l.gaps.length?<small className="funding-missing">Hisob to‘liq emas</small>:null}</td><td>{number(l.quantity)} {l.unit}</td><td>{number(l.workerHours)} / {number(l.operatorHours)}</td><td>{money(l.directCost)} so‘m</td><td><details><summary>{l.normReference}</summary><p>{l.frequencySource}</p>{l.gaps.map(g=><p key={g}>{g}</p>)}</details></td></tr>)}</tbody></table></TableFrame></Card>
   <Card><details><summary>Material va mashina-mexanizm hisoblari</summary><TableFrame label="Resurs xarajatlari"><table><thead><tr><th>Resurs</th><th>Yillik sarf</th><th>Birlik narxi</th><th>Summa</th></tr></thead><tbody>{(result?.resources??resourceRows).map(r=><tr key={r.key}><td>{r.name}<small>{r.kind==='machine'?'Mashina-mexanizm':'Material'} · {r.code}</small></td><td>{number(r.quantity)} {r.unit}</td><td>{r.price===null?'Narx kerak':money(r.price)}</td><td>{r.amount===null?'Aniqlashtiriladi':money(r.amount)}</td></tr>)}</tbody></table></TableFrame></details></Card>
   <Card><details><summary>IQN 03-24: jihozlar va xizmat muddati</summary><TableFrame label="Jihozlarning yillik xarajati"><table><thead><tr><th>Jihoz</th><th>Xizmat muddati</th><th>Yillik ulush</th><th>Summa</th><th>Asos</th></tr></thead><tbody>{result.ppeRows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.months?`${r.months} oy`:r.scope==='work'?'Ish hajmidan':'Manbada yo‘q'}</td><td>{r.scope==='work'?'Materiallar hisobida':`${number(r.quantity)} ${r.unit}`}<small>{r.scope==='personal'?`${r.heads} xodim × ${r.basisQuantity}`:r.scope==='division'?`${r.heads} bo‘lim`:r.scope==='worksite'?`${r.heads} ish joyi`:''}</small></td><td>{r.amount===null?'Narx kerak':money(r.amount)}</td><td>{r.source}</td></tr>)}</tbody></table></TableFrame></details></Card>
   <Card><details><summary>Texnik toifa bo‘yicha texnika parki ehtiyoji</summary><p className="field__hint">IQN 02-24, 3-ilova: 100 km uchun norma × yo‘l uzunligi. Bu park quvvati; xarid qiymati va yillik mashina-soat emas. Son umumiy foydalaniladigan park bo‘yicha yaxlitlanadi.</p><TableFrame label="Texnika parki"><table><thead><tr><th>Texnika</th><th>Hisobiy birlik</th><th>Yaxlitlangan park</th><th>Manba</th></tr></thead><tbody>{fleet.map(r=><tr key={r.source}><td>{r.name}<small>{r.specification}</small></td><td>{number(r.quantity)}{r.unavailable.length?<small>Norma berilmagan: {r.unavailable.join(', ')}</small>:null}</td><td>{Math.ceil(r.quantity)}</td><td>{r.source}</td></tr>)}</tbody></table></TableFrame></details></Card>
   <Card><details><summary>Hisob usuli va cheklovlar</summary><p>IQN 02-24, 1.13–1.14: xizmat hajmi yo‘l ahamiyati, texnik toifasi, jadalligi va holatiga qarab rejalashtiriladi. Umumiy pul koeffitsiyenti qo‘llanmagan.</p><p>Qoplama uchun holat ulushi × yillik davriylik hisoblanadi; o‘lchangan chuqurchalar bilan kattasi olinadi. Bu modulning takroriy hisobni oldini oluvchi rejalashtirish qoidasi. III–IV holatdagi zid davriylik rahbar tomonidan aniqlashtiriladi.</p>{result.warnings.map(w=><p key={w}>{w}</p>)}<p>Moliyalashtirish oylik fondi bo‘yicha: asosiy oylik × koeffitsiyent × ustama + ovqat puli + yillik bayram pulining 1/12 qismi. Ijtimoiy xarajat — ish haqidan; ustama xarajat — bevosita jami summadan; zaxira — shu jami va ustama xarajatdan. Xodimdan ushlanmalar ish beruvchi xarajatiga yana qo‘shilmaydi.</p></details></Card>
  </>:null}
  {tab==='assets'?<>
   <Card><div className="funding-topline"><div><h2>RAMS bilan almashish</h2><p className="field__hint">{integration==='ready'?'API ulangan. Yangilash aktivlarning yangi nusxasini oladi.':integration==='loading'?'Ulanish tekshirilmoqda…':integration==='error'?'Ulanish holati tekshirilmadi.':'RAMS API ulanmagan. Eksport faylini yuklash mumkin.'}</p></div>{canWrite?<div className="button-row"><Button variant="secondary" busy={busy} onClick={sync}><RefreshCw size={16}/> RAMS’dan yangilash</Button><label className="button button--secondary"><Upload size={16}/> Fayldan olish<input type="file" accept=".json,application/json" className="funding-file" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><Button variant="ghost" onClick={()=>download(JSON.stringify(snapshot,null,2),'RAMS-aktivlar.json')}>Format namunasi</Button></div>:null}</div></Card>
   <fieldset disabled={!canWrite} className="funding-fieldset">
    {selectedRoads.map(road=><Card key={road.id}><div className="funding-topline"><h2>{road.code} · {road.name}</h2><Button variant="secondary" onClick={()=>{const id=crypto.randomUUID();editRoad(road.id,{assets:[...road.assets,{id,kind:'OTHER',name:'Qo‘shimcha IQN ishi',quantity:1,unit:'dona',condition:'GOOD'}]});setActiveAsset(`${road.id}:${id}`);}}>Ish bandini qo‘shish</Button></div><div className="funding-form-grid"><SelectInput label="Yo‘l ahamiyati" name={`importance-${road.id}`} value={road.importance} onChange={e=>editRoad(road.id,{importance:e.target.value as Road['importance']})}>{Object.entries(importanceLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</SelectInput><SelectInput label="Texnik toifa" name={`category-${road.id}`} value={road.category} onChange={e=>editRoad(road.id,{category:e.target.value as Road['category']})}>{['Ia','Ib','II','III','IV','V'].map(v=><option key={v}>{v}</option>)}</SelectInput><SelectInput label="Yo‘lning umumiy holati" name={`condition-${road.id}`} value={road.condition} onChange={e=>editRoad(road.id,{condition:e.target.value as Road['condition']})}>{Object.entries(conditionLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</SelectInput><TextInput label="Uzunlik, km" name={`length-${road.id}`} type="number" min="0.001" value={road.lengthKm} onChange={e=>editRoad(road.id,{lengthKm:Number(e.target.value)})}/></div><TableFrame label={`${road.code} aktivlari`}><table><thead><tr><th>Aktiv</th><th>Miqdor</th><th>Holati</th><th>Nuqson hajmi</th><th/></tr></thead><tbody>{road.assets.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{assetLabels[a.kind]}</small></td><td><TextInput label={`Miqdor: ${a.name}, ${a.unit}`} name={`quantity-${road.id}-${a.id}`} type="number" min="0" step="any" value={a.quantity} onChange={e=>editAsset(road.id,a.id,{quantity:Number(e.target.value)})}/></td><td><SelectInput label={`Holat: ${a.name}`} name={`condition-${road.id}-${a.id}`} value={a.condition} onChange={e=>editAsset(road.id,a.id,{condition:e.target.value as Asset['condition']})}>{Object.entries(conditionLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</SelectInput></td><td><TextInput label={`Nuqson: ${a.name}, ${a.unit}`} name={`defect-${road.id}-${a.id}`} type="number" min="0" step="any" value={a.defectQuantity??''} onChange={e=>editAsset(road.id,a.id,{defectQuantity:e.target.value===''?undefined:Number(e.target.value)})}/></td><td><Button variant="secondary" onClick={()=>setActiveAsset(`${road.id}:${a.id}`)}>Ish va me’yor</Button></td></tr>)}</tbody></table></TableFrame></Card>)}
    {selection?<Card><h2>{selection.asset.name} · ish va me’yor</h2><TextInput label="Aktiv yoki ish bandi nomi" name="fundingAssetName" value={selection.asset.name} onChange={e=>editAsset(selection.road.id,selection.asset.id,{name:e.target.value})}/><div className="funding-form-grid"><SelectInput label="Ishni tanlash" name="fundingWorkId" value={selection.asset.workId??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{workId:e.target.value||undefined,workQuantity:undefined,workUnit:iqnWorkCatalog.find(w=>w.id===e.target.value)?.unit,resourcePlan:undefined})}><option value="">Aktiv bo‘yicha avtomatik</option>{iqnWorkCatalog.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name} · {w.unit}</option>)}</SelectInput>{selection.asset.workId?<TextInput label={`Bir bajarishdagi ish hajmi, ${currentWork?.unit??selection.asset.unit}`} name="fundingWorkQuantity" type="number" min="0" step="any" value={selection.asset.workQuantity??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{workQuantity:e.target.value===''?undefined:Number(e.target.value)})}/>:null}<TextInput label="Yillik davriylik (qo‘lda o‘zgartirish)" name="fundingFrequency" type="number" min="0.001" step="any" value={selection.asset.annualFrequency??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{annualFrequency:e.target.value===''?undefined:Number(e.target.value)})}/><TextInput label="Davriylik qarorining asosi" name="fundingFrequencyBasis" value={selection.asset.frequencyBasis??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{frequencyBasis:e.target.value})}/>
     {selection.asset.kind==='SIGN'?<SelectInput label="Sanoat hududi" name="industrialZone" value={selection.asset.industrialZone===undefined?'':String(selection.asset.industrialZone)} onChange={e=>editAsset(selection.road.id,selection.asset.id,{industrialZone:e.target.value===''?undefined:e.target.value==='true'})}><option value="">Belgilang</option><option value="true">Ha — 14 marta/yil</option><option value="false">Yo‘q — 10 marta/yil</option></SelectInput>:null}
     {['BARRIER','CURB','LIGHTING'].includes(selection.asset.kind)?<SelectInput label="Nuqson bo‘yicha ta’mir usuli" name="fundingRepairMethod" value={selection.asset.repairMethod??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{repairMethod:e.target.value as Asset['repairMethod']||undefined})}><option value="">Aniqlashtiring</option><option value="STRAIGHTEN">Mavjud elementni to‘g‘rilash</option><option value="REPLACE_FIXTURE">To‘liq yoritgichni almashtirish</option></SelectInput>:null}
     {selection.asset.kind==='PAVEMENT'?<><TextInput label="Ta’mir qalinligi, mm" name="fundingThickness" type="number" value={selection.asset.parameters?.thicknessMm??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{parameters:{...selection.asset.parameters,thicknessMm:Number(e.target.value)}})}/><TextInput label="Eng katta chuqurcha, m²" name="fundingPatchArea" type="number" step="any" value={selection.asset.parameters?.largestPatchM2??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{parameters:{...selection.asset.parameters,largestPatchM2:Number(e.target.value)}})}/><SelectInput label="Eski qoplamani buzish" name="fundingRemoveOld" value={selection.asset.parameters?.removeOld===undefined?'':String(selection.asset.parameters.removeOld)} onChange={e=>editAsset(selection.road.id,selection.asset.id,{parameters:{...selection.asset.parameters,removeOld:e.target.value===''?undefined:e.target.value==='true'}})}><option value="">Belgilang</option><option value="true">Ha</option><option value="false">Yo‘q</option></SelectInput></>:null}
     {currentWork?.normRange?<TextInput label={`Me’yor: ${currentWork.normRange.join('–')} kishi-soat / ${currentWork.normBasisQuantity} ${currentWork.unit}`} name="fundingSelectedNorm" type="number" step="any" min={currentWork.normRange[0]} max={currentWork.normRange[1]} value={selection.asset.selectedNormHours??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{selectedNormHours:e.target.value===''?undefined:Number(e.target.value)})}/>:null}{currentWork?.catalogSeries==='TIME'?<><TextInput label={`Mashinist soati / 1 ${currentWork.unit} (zarur bo‘lsa)`} name="fundingOperatorHours" type="number" min="0" step="any" value={selection.asset.operatorHoursPerUnit??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{operatorHoursPerUnit:e.target.value===''?undefined:Number(e.target.value)})}/><TextInput label="Mashinist mehnati asosi" name="fundingOperatorBasis" value={selection.asset.operatorBasis??''} onChange={e=>editAsset(selection.road.id,selection.asset.id,{operatorBasis:e.target.value})}/></>:null}
    </div>{currentWork?<PlanResources work={currentWork} catalog={iqnWorkCatalog} quantity={String(assetWorkSpecs(selection.asset,policy).find(s=>s.workId===currentWork.id)?.quantity??selection.asset.quantity)} value={selection.asset.resourcePlan} onChange={value=>editAsset(selection.road.id,selection.asset.id,{resourcePlan:value})}/>:null}<Button variant="secondary" onClick={()=>{setTab('estimate');setActiveAsset('');}}>Hisobga qaytish</Button></Card>:null}
   </fieldset>
  </>:null}
  {tab==='prices'?<fieldset disabled={!canWrite} className="funding-fieldset">
   <Card><h2>Ish haqi va yillik ish vaqti</h2><div className="funding-form-grid">{field('annualHours','Bir xodim yillik ish vaqti, soat')}{field('workerMonthly','Ishchi asosiy oyligi, so‘m')}{field('operatorMonthly','Mashinist asosiy oyligi, so‘m')}{field('supervisorMonthly','Yo‘l ustasi asosiy oyligi, so‘m')}{field('supervisors','Ustalar soni (bo‘sh = IQN)',true)}{field('wageCoefficient','Oylik koeffitsiyenti')}{field('allowancePercent','Ustama, %')}{field('holidayPerYear','Bir xodim bayram puli, so‘m/yil')}{field('mealPerMonth','Bir xodim ovqat puli, so‘m/oy')}{field('divisionCount','Yo‘l bo‘limlari soni')}<TextInput label="Bir vaqtdagi ish joylari" name="budget-worksites" type="number" min="0" value={policy.worksiteCount??1} onChange={e=>patch({worksiteCount:Number(e.target.value)})}/></div></Card>
   <Card><details><summary>Boshqaruv va xizmat ko‘rsatish shtati</summary><p className="field__hint">Odam soni — jihoz uchun; stavka — ish haqi uchun. Masalan, 0,5 stavkada 1 odam. Shtatni IQN 03-24, 5-jadval va tasdiqlangan tuzilma bilan asoslang.</p><TableFrame label="Qo‘shimcha shtat"><table><thead><tr><th>Lavozim</th><th>Odam</th><th>Stavka</th><th>Asosiy oylik</th><th>Asos</th></tr></thead><tbody>{['ytb_boshligi','energetik','mexanik','hht_muhandisi','other'].map(role=>{const row=policy.staff?.find(s=>s.role===role)??{role,heads:0,fte:0,monthly:0,basis:''};const edit=(changes:Partial<typeof row>)=>patch({staff:[...(policy.staff??[]).filter(s=>s.role!==role),{...row,...changes}]});return <tr key={role}><td>{staffRoles[role]}</td>{(['heads','fte','monthly'] as const).map(key=><td key={key}><TextInput label={`${staffRoles[role]} ${key==='heads'?'odam':key==='fte'?'stavka':'oylik'}`} name={`staff-${role}-${key}`} type="number" min="0" step={key==='heads'?1:'any'} value={row[key]} onChange={e=>edit({[key]:Number(e.target.value)})}/></td>)}<td><TextInput label={`${staffRoles[role]} asosi`} name={`staff-${role}-basis`} value={row.basis} onChange={e=>edit({basis:e.target.value})}/></td></tr>;})}</tbody></table></TableFrame></details></Card>
   <Card><details><summary>Boshqa xarajatlar tafsiloti</summary><p className="field__hint">Tarifga kiritilgan transport, saqlash va ish haqini qayta qo‘shmang.</p>{(policy.otherCosts??[]).map((row,i)=><div key={row.id} className="funding-form-grid">{(['name','amount','basis'] as const).map(key=><TextInput key={key} label={key==='name'?'Xarajat nomi':key==='amount'?'Yillik summa, so‘m':'IQN bandi va narx asosi'} name={`other-${row.id}-${key}`} type={key==='amount'?'number':'text'} value={row[key]} onChange={e=>patch({otherCosts:policy.otherCosts!.map((r,j)=>i===j?{...r,[key]:key==='amount'?Number(e.target.value):e.target.value}:r)})}/>)}</div>)}<Button variant="secondary" onClick={()=>patch({otherCosts:[...(policy.otherCosts??[]),{id:crypto.randomUUID(),name:'Xarajat',amount:0,basis:''}]})}>Xarajat qo‘shish</Button></details></Card>
   <Card><h2>Boshqa xarajatlar</h2><div className="funding-form-grid">{field('employerTaxPercent','Ish beruvchi ijtimoiy xarajati, %')}{field('overheadPercent','Ustama xarajat, %')}{field('contingencyPercent','Zaxira, %')}{field('otherAnnual','Boshqa asoslangan xarajat, so‘m/yil')}</div><TextArea label="Tariflar va xarajatlar asosi" name="fundingPolicyReference" value={policy.reference} onChange={e=>patch({reference:e.target.value})}/><p className="field__hint">Soliq va ustamalarni tashkilotingiz uchun amaldagi stavkada kiriting. Mashina tarifida yonilg‘i, ta’mir va amortizatsiya; material tarifida yetkazish va saqlash hisobga olingan bo‘lsa, qayta qo‘shmang.</p></Card>
   <Card><h2>III–IV holatdagi davriylik qarori</h2><p className="field__hint">IQN 02-24, 1-ilovada davr va takrorlanish soni bir-biriga zid. Tanlangan davriylik uchun asos kiriting.</p><div className="funding-form-grid">{field('conditionIIIRepeats','III holat — marta/yil',true)}{field('conditionIVRepeats','IV holat — marta/yil',true)}<TextInput label="Holat davriyligi asosi" name="conditionBasis" value={policy.conditionBasis} onChange={e=>patch({conditionBasis:e.target.value})}/></div></Card>
   <Card><h2>Material va mashina-soat narxlari</h2><p className="field__hint">Soliqlar hisobga olingan yakuniy birlik narxi. “Namuna” yozuvini haqiqiy narx manbasi bilan almashtiring.</p><TableFrame label="Budjet tariflari"><table><thead><tr><th>Resurs</th><th>Birlik</th><th>Narx, so‘m</th><th>Manba</th></tr></thead><tbody>{(result?.resources??resourceRows).map(r=><tr key={r.key}><td>{r.name}<small>{r.kind==='machine'?'Haydovchi oyligisiz':'Yetkazish va saqlash bilan'}</small></td><td>{r.unit}</td><td><TextInput label={`${r.name} narxi`} name={`rate-${r.key}`} type="number" min="0" step="any" value={policy.rates[r.key]?.price??''} onChange={e=>patch({rates:{...policy.rates,[r.key]:{...policy.rates[r.key],unit:r.unit,price:e.target.value===''?null:Number(e.target.value),source:policy.rates[r.key]?.source??'',includesOperator:false}}})}/></td><td><TextInput label={`${r.name} narx asosi`} name={`source-${r.key}`} value={policy.rates[r.key]?.source??''} onChange={e=>patch({rates:{...policy.rates,[r.key]:{...policy.rates[r.key],unit:r.unit,price:policy.rates[r.key]?.price??null,source:e.target.value,includesOperator:false}}})}/></td></tr>)}</tbody></table></TableFrame></Card>
   <Card><details><summary>IQN 03-24: jihoz narxi va berish miqdori</summary><TableFrame label="Jihoz narxlari"><table><thead><tr><th>Jihoz</th><th>Narx</th><th>Bir odamga berish miqdori</th><th>Yaroqli qoldiq</th></tr></thead><tbody>{equipmentNorms.filter(n=>n.scope!=='work').map(n=><tr key={n.id}><td>{n.name}<small>3-jadval, {n.row}-qator</small></td><td><TextInput label={`${n.name} narxi`} name={`ppe-${n.id}`} type="number" min="0" value={policy.equipmentPrices[n.id]??''} onChange={e=>patch({equipmentPrices:{...policy.equipmentPrices,[n.id]:e.target.value===''?null:Number(e.target.value)}})}/></td><td>{n.assumed?<TextInput label={`${n.name} berish miqdori`} name={`issue-qty-${n.id}`} type="number" min="0" step="any" value={policy.equipmentIssueQuantity?.[n.id]??1} onChange={e=>patch({equipmentIssueQuantity:{...policy.equipmentIssueQuantity,[n.id]:Number(e.target.value)}})}/>:n.quantity}</td><td>{!n.months?<TextInput label={`${n.name} yaroqli qoldiq`} name={`stock-${n.id}`} type="number" min="0" value={policy.equipmentStock?.[n.id]??0} onChange={e=>patch({equipmentStock:{...policy.equipmentStock,[n.id]:Number(e.target.value)}})}/>:"Yillik ulush hisobida"}</td></tr>)}</tbody></table></TableFrame><p className="field__hint">“+” belgi berilish huquqini bildiradi; 1 dona/juft — tahrirlanadigan hisob sharti. Xizmat muddati bor jihozda yillik moliyaviy ulush, muddati yo‘q jihozda birlamchi ehtiyojdan yaroqli qoldiq ayiriladi.</p></details></Card>
  </fieldset>:null}
  <Card><details><summary>Saqlangan hisoblar ({history.length})</summary><p className="field__hint">Nusxalar shu brauzerda saqlanadi. Fayl nusxasini “Yo‘llar va aktivlar → Fayldan olish” orqali qayta ochish mumkin.</p>{history.map(item=><div key={item.id} className="funding-history"><span>{item.policy.year}-yil · {new Date(item.at).toLocaleString('uz-UZ')}</span><Button variant="ghost" disabled={!canWrite} onClick={()=>{setSnapshot(item.snapshot);setPolicy(item.policy);setLimit(item.budgetLimit===null||item.budgetLimit===undefined?'':String(item.budgetLimit));setTab('estimate');setMessage('Saqlangan aktivlar va tariflar bilan hisob ochildi.');}}>Ochish</Button><Button variant="ghost" onClick={()=>download(JSON.stringify(item,null,2),`Saqlash-budjeti-${item.policy.year}.json`)}>Nusxani yuklash</Button></div>)}</details></Card>
 </div>;
}
